import './mainCtrl';
import './menuCtrl';
import './stepCtrl';
import './modalCtrl';
import './homeCtrl';
import './manageTemplateCtrl';
import './chooseTemplateCtrl';
import './manageTemplateCtrl';
import './simulateTemplateCtrl';