//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.IoT.Simulator.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.IoT.Simulator.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        /// </summary>
        public static string ChooseTemplateDescription {
            get {
                return ResourceManager.GetString("ChooseTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from your saved templates to simulate your device data..
        /// </summary>
        public static string ChooseTemplateSelectSaveTemplateDescription {
            get {
                return ResourceManager.GetString("ChooseTemplateSelectSaveTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Saved Templates.
        /// </summary>
        public static string ChooseTemplateSelectSaveTemplateTitle {
            get {
                return ResourceManager.GetString("ChooseTemplateSelectSaveTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate Your Product.
        /// </summary>
        public static string ChooseTemplateTitle {
            get {
                return ResourceManager.GetString("ChooseTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UART: Connected.
        /// </summary>
        public static string FooterUARTConnected {
            get {
                return ResourceManager.GetString("FooterUARTConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UART: Disconnected.
        /// </summary>
        public static string FooterUARTDisconnected {
            get {
                return ResourceManager.GetString("FooterUARTDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB: Connected.
        /// </summary>
        public static string FooterUSBConnected {
            get {
                return ResourceManager.GetString("FooterUSBConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB: Disconnected.
        /// </summary>
        public static string FooterUSBDisconnected {
            get {
                return ResourceManager.GetString("FooterUSBDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string HeaderSignOutButton {
            get {
                return ResourceManager.GetString("HeaderSignOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Goods Data Packet Simulator.
        /// </summary>
        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string HomeLoginButton {
            get {
                return ResourceManager.GetString("HomeLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security of an internet connected device requires continuous renewal.
        ///
        ///With 4x4, Microsoft is sharing over 20 years of experience in protecting internet connected devices.
        ///
        ///This simulator will help you get started with your 4x4. With it, you will be able to:
        ///- Select a template from the Data Packet Designer
        ///- Preview some sample data
        ///- Send data to the 4x4
        ///- Watch the data being retrieved from Azure IoT Hub in real time.
        ///
        ///To get started, please login..
        /// </summary>
        public static string HomeProductDescription {
            get {
                return ResourceManager.GetString("HomeProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x4 Chip Summary.
        /// </summary>
        public static string HomeProductTitle {
            get {
                return ResourceManager.GetString("HomeProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected !.
        /// </summary>
        public static string PreviewTemplateChipStatusConnected {
            get {
                return ResourceManager.GetString("PreviewTemplateChipStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before starting the simulation, please make sure that:
        ///- Your chip was properly initialized and is connected through wifi.
        ///- Your chip is powered through USB to your computer.
        ///- Your chip is connected to a Serial Port dongle (UART) to your computer..
        /// </summary>
        public static string PreviewTemplateChipStatusDescription {
            get {
                return ResourceManager.GetString("PreviewTemplateChipStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string PreviewTemplateChipStatusDisconnected {
            get {
                return ResourceManager.GetString("PreviewTemplateChipStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of your 4x4 chip.
        /// </summary>
        public static string PreviewTemplateChipStatusTitle {
            get {
                return ResourceManager.GetString("PreviewTemplateChipStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template will be used to generate a JSON string containing randomized data. 
        ///In the next screen, the simulator will take the role of a connected device, sending updated data to your 4x4.
        ///The 4x4 will then forward these messages to IoT Hub..
        /// </summary>
        public static string PreviewTemplateDataPreviewDescription {
            get {
                return ResourceManager.GetString("PreviewTemplateDataPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Template Data.
        /// </summary>
        public static string PreviewTemplateDataPreviewTitle {
            get {
                return ResourceManager.GetString("PreviewTemplateDataPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string PreviewTemplateRetryButton {
            get {
                return ResourceManager.GetString("PreviewTemplateRetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your UART dongle:.
        /// </summary>
        public static string PreviewTemplateSelectDongle {
            get {
                return ResourceManager.GetString("PreviewTemplateSelectDongle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate !.
        /// </summary>
        public static string PreviewTemplateSimulateButton {
            get {
                return ResourceManager.GetString("PreviewTemplateSimulateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        public static string SelectTemplateRefreshButton {
            get {
                return ResourceManager.GetString("SelectTemplateRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Data Packet.
        /// </summary>
        public static string SimulateReceivingFirstRow {
            get {
                return ResourceManager.GetString("SimulateReceivingFirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Cosmos DB.
        /// </summary>
        public static string SimulateReceivingSecondRow {
            get {
                return ResourceManager.GetString("SimulateReceivingSecondRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Simulation.
        /// </summary>
        public static string SimulateRestartButton {
            get {
                return ResourceManager.GetString("SimulateRestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending messages through.
        /// </summary>
        public static string SimulateSendingFirstRowTitle {
            get {
                return ResourceManager.GetString("SimulateSendingFirstRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x4 chip to IoT Hub.
        /// </summary>
        public static string SimulateSendingSecondRowTitle {
            get {
                return ResourceManager.GetString("SimulateSendingSecondRowTitle", resourceCulture);
            }
        }
    }
}
